### ISSUE TITLE
Dealer can reveal the scores forcibly.

### ISSUE THREAD

**Issue by callas1900** [callas1900/planning_poker#65]

**Comment by cont-mmishina** [comment]
参加者が一時的に投票できないことがあり、その場合プランニングポーカーを進めることができない。
そのため、ディーラーは強制的に投票を終え、結果を表示できるようにして欲しい。

受入条件
・ディーラーは未投票者がいても強制的に投票を終え、結果を表示することができる
・未投票者分は未投票がわかるようになっていて、他の投票に影響がない
・未投票でも、次のポーカーには参加できる
